### ISSUE TITLE
#define CLOUD_CLIENT_KEY 没有定义

### ISSUE THREAD

**Issue by smallhorse87** [JGINGIT/Telespot#1]
工程里没有定义#define CLOUD_CLIENT_KEY ，这个值具体是做什么用的？随便定义一个值，是否也可以？

**Comment by JesseGuoX** [comment]
@smallhorse87  Telespot后端使用的是[Parse](https://www.parse.com)的Baas服务，`CLOUD_CLIENT_KEY`和 `CLOUD_APPLICATION_ID`是[Parse](https://www.parse.com) 提供的，需要在[Parse](https://www.parse.com)里面新建一个App，就可以得到相应的`KEY`和`ID`

**Comment by smallhorse87** [comment]
Baas是类似提供了接口服务吗？通常来讲，我们都会有个专门的服务器端开发人员来开发服务器端的业务逻辑，并设计一些接口服务，APP和服务器端通过接口进行通信。这个Baas也需要设计服务器端业务代码吗？

**Comment by smallhorse87** [comment]
建议您可以建一个演示用Parse的账号

**Comment by JesseGuoX** [comment]
@smallhorse87 通常来讲是要一个服务器开发人员开发后端程序，并设计一些接口与 App 通信，那我们为什么不能直接把别人打包封装好的后端服务拿来用呢？[Parse](https://parse.com/)提供了相当多的应用实例和详细的API文档，如果访问不了的话可以看国内的 [LeanCloud](https://leancloud.cn)，提供的服务类似。但是 Telespot 是基于 Parse 开发的，所以不能直接用 LeanCloud 的Key 和 ID。

**Comment by smallhorse87** [comment]
👍
